import type {Metadata} from "next";
import "./globals.css";
import {Navbar} from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={"dark bg-background-50 text-text-950 font-NotoSans"}
        >
        <Navbar/>
        <main className="px-8 md:px-24 lg:px-48 xl:px-72 2xl:px-96">
            {children}
        </main>
        </body>
        </html>
    );
}
