import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "next-themes";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="bg-background-50 text-text-950 text-lg font-Fredoka">
            <ThemeProvider attribute="class">
                {children}
            </ThemeProvider>
        </body>
        </html>
    );
}

export default RootLayout;